const escapeCStr = (s = '') => (s || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');

// PUBLIC_INTERFACE
export function generateCSource(config) {
  /**
   * Generate a single-file main.c program performing DNS queries via a specific interface.
   * Uses BSD sockets, sets SO_BINDTODEVICE (Linux) if provided.
   */
  const {
    domain = 'example.com',
    dnsServer = '8.8.8.8',
    iface = '',
    qtype = 'A',
    timeout = 3,
    retries = 2,
  } = config || {};

  const qtypeMap = {
    A: 1,
    AAAA: 28,
    CNAME: 5,
    TXT: 16,
    MX: 15,
    NS: 2,
    SRV: 33,
  };
  const qtypeCode = qtypeMap[qtype] || 1;

  const ifaceComment = iface ? `// Attempt to bind outgoing socket to interface: ${iface}` : '// No interface binding requested';

  return `/*
  DNS Query Utility - Generated by DNS Query UI
  Compile:
    gcc -o dns_query main.c

  Run:
    sudo ./dns_query

  Notes:
    - On Linux, this attempts to set SO_BINDTODEVICE to direct traffic via the specified interface.
    - Requires sudo/root when using SO_BINDTODEVICE.
    - This is a simplified resolver example for educational and utility purposes.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifdef __linux__
#include <net/if.h>
#endif

#define DNS_PORT 53
#define BUF_SIZE 512

// DNS header structure
struct DNS_HEADER {
    unsigned short id;
    unsigned char rd :1;
    unsigned char tc :1;
    unsigned char aa :1;
    unsigned char opcode :4;
    unsigned char qr :1;

    unsigned char rcode :4;
    unsigned char z :3;
    unsigned char ra :1;

    unsigned short q_count;
    unsigned short ans_count;
    unsigned short auth_count;
    unsigned short add_count;
};

// Question structure
struct QUESTION {
    unsigned short qtype;
    unsigned short qclass;
};

static void change_to_dns_name_format(unsigned char* dns, const char* host) {
    int lock = 0 ;
    char hostdup[256];
    memset(hostdup, 0, sizeof(hostdup));
    strncpy(hostdup, host, sizeof(hostdup)-1);
    strcat(hostdup, ".");
    for (int i = 0 ; i < (int)strlen(hostdup) ; i++) {
        if(hostdup[i] == '.') {
            *dns++ = i - lock;
            for(; lock < i; lock++) {
                *dns++ = hostdup[lock];
            }
            lock++;
        }
    }
    *dns++ = '\0';
}

static int set_timeout(int sock, int t) {
    struct timeval tv;
    tv.tv_sec = t;
    tv.tv_usec = 0;
    if (setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv)) < 0) return -1;
    if (setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv)) < 0) return -1;
    return 0;
}

int main() {
    const char* domain = "${escapeCStr(domain)}";
    const char* dns_server = "${escapeCStr(dnsServer)}";
    const char* iface = "${escapeCStr(iface)}";
    int qtype = ${qtypeCode};
    int timeout_sec = ${timeout};
    int retry_count = ${retries};

    unsigned char buf[BUF_SIZE];
    unsigned char *qname;
    struct DNS_HEADER *dns = NULL;
    struct QUESTION *qinfo = NULL;

    int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (sock < 0) {
        perror("socket");
        return 1;
    }

    // Timeouts
    if (set_timeout(sock, timeout_sec) != 0) {
        perror("setsockopt timeout");
        // continue even if failed
    }

    ${ifaceComment}
#ifdef __linux__
    if (iface[0] != '\\0') {
        if (setsockopt(sock, SOL_SOCKET, SO_BINDTODEVICE, iface, strlen(iface)) < 0) {
            perror("SO_BINDTODEVICE (requires root)");
            // continue without binding
        }
    }
#else
    (void)iface; // unused on non-Linux
#endif

    struct sockaddr_in dest;
    dest.sin_family = AF_INET;
    dest.sin_port = htons(DNS_PORT);
    if (inet_pton(AF_INET, dns_server, &dest.sin_addr) != 1) {
        fprintf(stderr, "Invalid DNS server IP: %s\\n", dns_server);
        close(sock);
        return 1;
    }

    memset(buf, 0, BUF_SIZE);
    dns = (struct DNS_HEADER *)&buf;

    // Random-ish ID
    dns->id = (unsigned short) htons(getpid());
    dns->qr = 0;
    dns->opcode = 0;
    dns->aa = 0;
    dns->tc = 0;
    dns->rd = 1;
    dns->ra = 0;
    dns->z = 0;
    dns->rcode = 0;
    dns->q_count = htons(1);
    dns->ans_count = 0;
    dns->auth_count = 0;
    dns->add_count = 0;

    qname = (unsigned char*)&buf[sizeof(struct DNS_HEADER)];
    change_to_dns_name_format(qname, domain);
    qinfo = (struct QUESTION*)&buf[sizeof(struct DNS_HEADER) + (strlen((const char*)qname) + 1)];
    qinfo->qtype = htons((unsigned short)qtype);
    qinfo->qclass = htons(1); // IN

    int packet_len = sizeof(struct DNS_HEADER) + (strlen((const char*)qname) + 1) + sizeof(struct QUESTION);

    int attempts = 0;
    socklen_t slen = sizeof(dest);
    int received = -1;
    while (attempts <= retry_count) {
        attempts++;
        if (sendto(sock, (char*)buf, packet_len, 0, (struct sockaddr*)&dest, slen) < 0) {
            perror("sendto");
            continue;
        }
        received = recvfrom(sock, (char*)buf, BUF_SIZE, 0, (struct sockaddr*)&dest, &slen);
        if (received >= (int)sizeof(struct DNS_HEADER)) {
            break;
        } else if (received < 0) {
            perror("recvfrom");
        }
    }

    if (received < 0) {
        fprintf(stderr, "DNS query failed after %d attempts.\\n", attempts-1);
        close(sock);
        return 1;
    }

    struct DNS_HEADER *resp = (struct DNS_HEADER*)buf;
    int ancount = ntohs(resp->ans_count);
    printf("Received DNS response. Answers: %d\\n", ancount);
    // NOTE: For brevity, this example doesn't fully parse all RR types.
    // It validates that a response arrived and prints answer count.

    close(sock);
    return 0;
}
`;
}

// PUBLIC_INTERFACE
export function downloadTextFile(filename, content) {
  /** Trigger browser download for a text file. */
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// PUBLIC_INTERFACE
export async function copyToClipboard(text) {
  /** Copy text to clipboard with fallback. */
  if (navigator.clipboard && window.isSecureContext) {
    await navigator.clipboard.writeText(text);
    return true;
  }
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.left = '-9999px';
  document.body.appendChild(ta);
  ta.focus();
  ta.select();
  let ok = false;
  try {
    ok = document.execCommand('copy');
  } catch (e) {
    ok = false;
  }
  ta.remove();
  return ok;
}
