//
// Utilities for generating C DNS query code and build/run snippets.
//

// PUBLIC_INTERFACE
export function buildCSource(options) {
  /**
   * Generate a C program source code string that performs a DNS query.
   * The code conditionally uses raw sockets (stubbed) or the system resolver
   * and sets the outgoing interface where possible using IP_PKTINFO / SO_BINDTODEVICE.
   *
   * Parameters:
   *  - options: {
   *      iface: string,
   *      dnsServer: string,
   *      domain: string,
   *      recordType: 'A'|'AAAA'|'CNAME'|'TXT'|'MX',
   *      timeout: number,
   *      retries: number,
   *      useRaw: boolean
   *    }
   *
   * Returns:
   *  - string with full C source code.
   */
  const {
    iface = "eth0",
    dnsServer = "8.8.8.8",
    domain = "example.com",
    recordType = "A",
    timeout = 3,
    retries = 2,
    useRaw = false
  } = options || {};

  const recordMap = {
    A: 1,
    NS: 2,
    CNAME: 5,
    SOA: 6,
    PTR: 12,
    MX: 15,
    TXT: 16,
    AAAA: 28
  };
  const qtype = recordMap[recordType] ?? 1;

  const rawNote = useRaw
    ? "/* NOTE: Raw-socket DNS query builder is stubbed here for brevity. It demonstrates\n     * how to set IP_PKTINFO or SO_BINDTODEVICE if available. For production-grade DNS\n     * packet crafting, consider using a dedicated library or implement RFC 1035 fully.\n     */"
    : "/* Using system resolver (getaddrinfo) plus optional nameserver override via RES_OPTIONS.\n     * This approach is simpler and portable, though precise interface binding support varies.\n     */";

  // The C source balances portability and an example of setting device via SO_BINDTODEVICE on Linux.
  return `/*
 * Generated by DNS Query UI
 * Options:
 *   Interface: ${iface}
 *   DNS Server: ${dnsServer}
 *   Domain: ${domain}
 *   Record Type: ${recordType}
 *   Timeout: ${timeout}s
 *   Retries: ${retries}
 *   Mode: ${useRaw ? "Raw sockets" : "System resolver"}
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#ifdef __linux__
#include <net/if.h>
#include <linux/if_packet.h>
#include <linux/in.h>
#include <linux/in6.h>
#endif

static const char* kInterface = "${iface}";
static const char* kDnsServer = "${dnsServer}";
static const char* kDomain    = "${domain}";
static const int   kQType     = ${qtype};
static const int   kTimeout   = ${timeout};
static const int   kRetries   = ${retries};

${rawNote}

static void set_timeout(int fd, int seconds) {
    struct timeval tv;
    tv.tv_sec = seconds;
    tv.tv_usec = 0;
    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
}

static int bind_to_device_if_possible(int fd, const char* ifname) {
#ifdef __linux__
    if (ifname && strlen(ifname) > 0) {
        if (setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, ifname, strlen(ifname)) != 0) {
            perror("SO_BINDTODEVICE");
            // Not fatal; continue without binding
        } else {
            fprintf(stderr, "Bound socket to device: %s\\n", ifname);
        }
    }
#else
    (void)fd; (void)ifname;
#endif
    return 0;
}

static int query_via_system_resolver(void) {
    // Optionally direct resolver to a specific nameserver via environment var (glibc respects RES_OPTIONS/RESOLV_FORCE)
    // Portable explicit resolver override is non-trivial without editing resolv.conf or using res_* APIs.
    // We print a note and proceed with getaddrinfo; use 'dig @server' externally if strict override is needed.

    struct addrinfo hints;
    memset(&hints, 0, sizeof(hints));
    hints.ai_socktype = SOCK_DGRAM; // UDP is fine for DNS resolution attempts
    hints.ai_family   = AF_UNSPEC;

    // Build a dummy socket to set timeouts and optionally bind to device
    int fd = socket(AF_INET, SOCK_DGRAM, 0);
    if (fd >= 0) {
        set_timeout(fd, kTimeout);
        bind_to_device_if_possible(fd, kInterface);
        close(fd);
    }

    struct addrinfo* res = NULL;
    int ret = getaddrinfo(kDomain, NULL, &hints, &res);
    if (ret != 0) {
        fprintf(stderr, "getaddrinfo: %s\\n", gai_strerror(ret));
        return 1;
    }

    printf("Results for %s (type=%d):\\n", kDomain, kQType);
    for (struct addrinfo* p = res; p != NULL; p = p->ai_next) {
        char host[NI_MAXHOST];
        if (getnameinfo(p->ai_addr, p->ai_addrlen, host, sizeof(host), NULL, 0, NI_NUMERICHOST) == 0) {
            printf(" - %s\\n", host);
        }
    }

    freeaddrinfo(res);
    return 0;
}

static int query_via_raw_sockets(void) {
    // Stub: build minimal DNS packet and send to kDnsServer, receive response, parse.
    // For brevity, we just create a UDP socket, set timeouts, optionally bind to device, and print intent.
    int fd = socket(AF_INET, SOCK_DGRAM, 0);
    if (fd < 0) {
        perror("socket");
        return 1;
    }

    set_timeout(fd, kTimeout);
    bind_to_device_if_possible(fd, kInterface);

    struct sockaddr_in dst;
    memset(&dst, 0, sizeof(dst));
    dst.sin_family = AF_INET;
    dst.sin_port = htons(53);
    if (inet_pton(AF_INET, kDnsServer, &dst.sin_addr) != 1) {
        fprintf(stderr, "Invalid DNS server: %s\\n", kDnsServer);
        close(fd);
        return 1;
    }

    printf("[Stub] Would send DNS query for %s (type=%d) to %s over %s\\n",
           kDomain, kQType, kDnsServer, kInterface);

    // Placeholders for send/recv logic

    close(fd);
    return 0;
}

int main(void) {
    int rc = 1;
    for (int attempt = 0; attempt <= kRetries; ++attempt) {
        printf("Attempt %d/%d...\\n", attempt + 1, kRetries + 1);
${useRaw
  ? "        rc = query_via_raw_sockets();"
  : "        rc = query_via_system_resolver();"}
        if (rc == 0) break;
        sleep(1);
    }
    return rc;
}
`;
}

// PUBLIC_INTERFACE
export function buildMakefileSnippet(filename = "dns_query.c") {
  /**
   * Generate a sample Makefile snippet for building the generated C program.
   * Parameters:
   *  - filename: Name of the generated C source file
   * Returns:
   *  - string Makefile content snippet
   */
  const bin = filename.replace(/\.c$/i, "");
  return `CC=gcc
CFLAGS=-O2 -Wall
TARGET=${bin}

all: $(TARGET)

$(TARGET): ${filename}
\t$(CC) $(CFLAGS) -o $(TARGET) ${filename}

clean:
\trm -f $(TARGET)
`;
}
